# Question : 
# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
# If the input is s = "abcd" & t = "abcde", then the output should be "e".

# Answer

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s = sorted(s)
        t = sorted(t)
        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]
        return t[-1]

sol = Solution()
s = "abcd"
t = "abcde"
res = sol.findTheDifference(s, t)
print(res)